// <auto-generated />
namespace RestaurantPaymentSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameItemNameAndAddSubcategoryIdToItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameItemNameAndAddSubcategoryIdToItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201903291053010_RenameItemNameAndAddSubcategoryIdToItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
